project:
  type: website
  output-dir: docs
website:
  title: "Chloe Pei-Hsin Huang's Research Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Research"
        menu:
          - text: "Research interests"
            href: research.qmd
          - text: "Publications"
            href: publications.qmd
      - text: "Projects"
        menu:
          - text: "Cross-cultural"
            href: projects/cultural.qmd
          - text: "Data visualisation"
            href: projects/visualisation.qmd
          - text: "Learning R"
            href: projects/R.qmd
      - text: "Blog"
        href: blog.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left

editor: visual