project:
  type: website
  output-dir: docs
website:
  title: "Chloe Pei-Hsin Huang's Research Blog"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Blog"
      - text: "Learning"
        menu:
          - text: "Data visualisation"
            href: projects/visualisation.qmd
          - text: "R"
            href: projects/R.qmd
          - text: "Theory"
            href: projects/theory.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: left

editor: visual